### ISSUE TITLE
Add ts settings

### ISSUE THREAD

**Issue by toothless8392** [skku-comit/comit-website-api#3]
### Describe the feature
The new folder "src" and "dist" are added. These are input and output of tsc respectively.
Src folder has ts files and dist folder has js files which are compiled by tsc.

**Comment by B0XERCAT** [comment]
@toothless8392 브랜치 이름을 feature/3-add-ts-settings 처럼 지어주시고
assignees labels 설정 해주시면 됩니다~ 오늘 회의 때 다시 설명드릴게요~
